### ISSUE TITLE
Combat freeze after selecting Garet's Djinn option

### ISSUE THREAD

**Issue by JCalHij** [jjppof/goldensun_html5#546]
While battling Briggs and its party, the whole game froze. Logs show this error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at g.preview_djinn_change (MainChar.ts:608:36)
    at e.DjinnStatsWindow.set_stats (DjinnStatsWindow.ts:107:42)
    at e.DjinnStatsWindow.set_djinn (DjinnStatsWindow.ts:131:14)
    at e.BattleDjinnWindow.update_stats (BattleDjinnWindow.ts:251:27)
    at e.BattleDjinnWindow.mount_window (BattleDjinnWindow.ts:259:14)
    at e.BattleDjinnWindow.open (BattleDjinnWindow.ts:375:14)
    at e.MainBattleMenu.on_ability_choose (MainBattleMenu.ts:227:16)
    at e.MainBattleMenu.inner_button_press (MainBattleMenu.ts:185:22)
    at e.HorizontalMenu.on_press (HorizontalMenu.ts:75:51)
    at e.ControlManager.p (ControlManager.ts:247:29)
```

I chose a Djinn from Isaac, then tried to choose a Djinn action for Garet.

![image](https://github.com/jjppof/goldensun_html5/assets/38001598/113bb91b-0dbe-46dc-b8d6-b9a0b3264f16)

**Comment by jjppof** [comment]
I'll be taking a look at it. Many thanks for finding it!

**Comment by jjppof** [comment]
I wasn't able to reproduce it.
That's a weird issue, how were you able to make Garet become a Squire?
The error msg you pointed seems to be class related.
What's the djinn configuration you used?
Did you make any changes in class_db.json?
If you can give a more specific step-by-step to reproduce the issue, it's going to help a lot.

Many thanks!

**Comment by JCalHij** [comment]
I have tried reproducing it as well in the demo, but I wasn't able either. As far as I know, I got the Mars Djinn that appears on town, grabbed a couple chests then fought Briggs. 

>What's the djinn configuration you used?

Only Djinn swap was between Isaac and Garet (Flint <-> Fever).
I cannot remember the exact things I did during combat, but I revived Garet on the previous turn with Quartz.

> Did you make any changes in class_db.json?

Playing directly on the browser demo.

> That's a weird issue, how were you able to make Garet become a Squire?

I think the engine might be holding some reference to Isaac or something, as it is not possible that Garet becomes a Squire.

**Comment by jjppof** [comment]
> I think the engine might be holding some reference to Isaac or something, as it is not possible that Garet becomes a Squire.

That's a good point, will check something in this sense.

Thanks
